version: '3.9'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-operadora_saude}
    # Mapeie para 3307 no host para evitar conflito com MySQL local
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql+pymysql://root:${MYSQL_ROOT_PASSWORD:-rootpassword}@db/${MYSQL_DATABASE:-operadora_saude}}
      SECRET_KEY: ${SECRET_KEY:-change-me}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    # For live reload during development, uncomment the following lines and run Flask directly
    # volumes:
    #   - .:/app
    # command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
